module.exports = Object.freeze({
  NAME_MIN_LENGTH: 3,
  CONTACT_LENGTH: 10,
  PINCODE_LENGTH: 6,

  VENDOR_PROFILE_QUEUED_STATUS: "queued",
  VENDOR_PROFILE_REVIEW_STATUS: "review",
  VENDOR_PROFILE_VERIFY_STATUS: "verified",

  VENDOR_PROFILE_SUBSCRIPTION_VERIFY_STATUS: "verification",
  VENDOR_PROFILE_SUBSCRIPTION_SUBSCRIBED_STATUS: "subscribed",
  VENDOR_PROFILE_SUBSCRIPTION_UNSUBSCRIBED_STATUS: "unsubscribed",
  VENDOR_PROFILE_SUBSCRIPTION_FREEZE_STATUS: "freeze",

  ADS_QUEUED_STATUS: "queued",
  ADS_REVIEW_STATUS: "review",
  ADS_ACTIVE_STATUS: "active",
  ADS_EXPIRED_STATUS: "expired",
  ADS_FREEZE_STATUS: "freeze",

  REVIEW_SKIP_HRS: 6,

  PRIORITY_ELITE: 1,
  PRIORITY_PREMIUM: 2,
  PRIORITY_STANDARD: 3,
});
