module.exports = Object.freeze({
  NAME_MIN_LENGTH: 3,
  CONTACT_LENGTH: 10,
  PINCODE_LENGTH: 6,
  VENDOR_PROFILE_QUEUED_STATUS: "queued",
  VENDOR_PROFILE_VERIFY_STATUS: "verified",
  VENDOR_PROFILE_REVIEW_STATUS: "review",
  VENDOR_PROFILE_INITIAL_SUBSCRIPTIONS_STATUS: "verification",
  ADS_INITIAL_VERIFY_STATUS: "queued",
  ADS_ACTIVE_STATUS: "active",
  REVIEW_SKIP_HRS: 6,
});
